version : '3'
services:
   postgres:
      image= "postgres:latest"
   redis:
      image= redis:latest
    ngix: 
      Restart=always
   server:
      build:
        dockerfile: Dockerfile.dev
        context: ./server
      volumes:
        - /app/node_modules
        - ./server:/app
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - POSTGRES_PASSWORD="postgres"
        - PGPORT=5432
        

         build:
           dockerfile: Dockerfile.dev
           context: .
           ports:
            - "3050:80"
    client:
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      volumes:
         - /app/node_modules
         - ./client:/app
    worker:
      build:
        dockerfile:dockerfile.dev
        context: ./worker
        volumes:
          - /app/node_modules
          - ./worker:app
