version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    variables:
        - POSTGRES_DB: nice_marmot
        - POSTGRES_USER: runner
        - POSTGRES_PASSWORD: "12345"
        - POSTGRES_HOST_AUTH_METHOD: trust
 
    